### ISSUE TITLE
f droid

### ISSUE THREAD

**Issue by NSTAdventure** [urbandroid-team/dontkillmy-app#10]
man how i can download this app from F-droid?

**Comment by yashpalgoyal1304** [comment]
did u try searching in fdroid?  
geez. basic stuff.

**Comment by NSTAdventure** [comment]
> did u try searching in fdroid?
> basic stuff.
> 
> this issue can be closed as duplicate of #1

nope in my f droid app i not found it why you not upload app on f droid? or did i do something wrong?

**Comment by yashpalgoyal1304** [comment]
addressing in #1 itself

**Comment by NSTAdventure** [comment]
> addressing in #1 itself

MOOOOOOMMMMYYYYY! 😭😭😭😭😭
